include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  errors:
    missing_required_param: error

linter:
  rules:
    # Performance
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

    # Crash Prevention
    null_check_on_nullable_type_parameter: true
    unnecessary_null_checks: true
    use_build_context_synchronously: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true

    # Code Quality
    use_key_in_widget_constructors: true
    avoid_print: true
    type_annotate_public_apis: true

    # Null Safety
    prefer_null_aware_operators: true

    # Anti-Patterns
    avoid_function_literals_in_foreach_calls: true
    unawaited_futures: true
