name: cheeko_mqtt
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^6.5.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_sound: ^9.28.0
  flutter_tts: ^4.2.3
  http: ^1.4.0
  model_viewer_plus: ^1.9.3
  mqtt_client: ^10.10.0
  opus_dart: ^3.0.1
  opus_flutter: ^3.0.1
  permission_handler: ^12.0.1
  provider: ^6.1.5
  record: ^6.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
